package uk.ac.warwick.dcs.visualisation;

import uk.ac.warwick.dcs.model.messaging.ModelUpdate;

/**
 * Interface implemented by a single models visualisation to
 * allow it to receive updates for the values generated by the
 * model itself. These updates can be consumed however they wish
 * to be.
 */
public interface IModelVisualisation {
    /**
     *
     * @return The name of the configuration represented by the
     *         <code>Model</code> object this object instance is
     *         visualising.
     */
    String getModelName();

    /**
     * Receive an update from the model
     * @param update The update received.
     */
    void notify(ModelUpdate update);
}
